<?php
/**
 * Created by PhpStorm.
 * User: youxingxiang
 * Date: 2020/8/19
 * Time: 11:43 AM
 */
namespace Quick\Admin;

use think\Service;

class AdminService extends Service
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
